Resources:
  NotariesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}-notaries
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      AttributeDefinitions:
        - AttributeName: PublicKey
          AttributeType: S
      KeySchema:
        - AttributeName: PublicKey
          KeyType: HASH

  NotariesPrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${opt:stage, self:provider.stage}-notaries
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedOrigins: ['*']
            AllowedMethods: [PUT, GET, HEAD]
