Resources:
  ParticipantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}-participants
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      AttributeDefinitions:
        - AttributeName: PublicKey
          AttributeType: S
      KeySchema:
        - AttributeName: PublicKey
          KeyType: HASH
