Resources:
  WSSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}-wssessions
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      AttributeDefinitions:
        - AttributeName: ConnectionID
          AttributeType: S
        - AttributeName: OrderID
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ByOrderID
          KeySchema:
          - AttributeName: OrderID
            KeyType: HASH
          - AttributeName: ConnectionID
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  WSSessionsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: ${self:service}-${opt:stage, self:provider.stage}-wssessions
